---
title: "Homepage"
links:
  text: Brown University
  href: https://vivo.brown.edu/display/kmcconeg
---

# About this site {.unnumbered}

The current tutorial version demonstrates a basic start to finish example of the "Clone-Censor-Weight" approach. The tutorial is a work in progress, and continually updated based on feedback, advances in science or as solutions to particular problems become known. 

# About the author

I am a pharmacoepidemiologist, and infectious diseases-trained pharmacist. My primary appointment is with the Providence VA Healthcare System. I am an investigator at the [THRIVE COIN](https://hsrd.research.va.gov/centers/thrive/investigators.cfm). I also am an adjunct assistant professor at Brown University [Link](https://vivo.brown.edu/display/kmcconeg). 

## Acknowledgements {.unnumbered}

The tutorial represents my gathered and organized notes from research projects and didactic training. Collaborators and mentors include: Issa Dahabreh, Kaley Hayes, Daniel Harris, Donald Miller and Andrew Zullo.

# Versions {.unnumbered}  

{{< include NEWS.md >}}