---
title: "CCW Tutorial"
subtitle: "Tutorial for Clone-Censor-Weighting Analyses"
bibliography: references.bib
---

## Welcome! {#welcome} 

This website is provided as a guide to help researchers interested in applying target trial emulation methods, specifically use of the "clone-censor-weight" or CCW approach.  

CCW is popular in the pharmacoepidemiology field, but its execution can be tricky. A TTE need not be done use CCW, but the approach is popular due to its flexibility. This website will provide a step-by-step guide on how to use this method. I also provide some in-depth discussions of particular aspects of the method, best practices, how to overcome common obstacles etc.

## Sections of this website {#sections}

1. [Survival Analysis](surv_00_summ.qmd). While not strictly about CCW, the first section of website provides some background for the most common statistical analyses techniques that are used when doing CCW in practice. [non-parametric analyses](surv_01_kaplan.qmd) can be used for simple examples but most researchers are using [pooled logistic regressions](surv_02_disctime.qmd) to approximate hazard ratios. I explain this in some detail and provide references to gain further understanding. Being comfortable with parametric discrete survival time analyses is crucial to properly executing more complex CCW analyses with time-varying confounders. 

2. [Clone-Censor-Weight](ccw_00_summ.qmd). The primary section of this website is the stepwise guide on how to do a CCW analysis. This includes: [background discussion](ccw_01_intro.qmd), [estimation](ccw_02_est.qmd), [inference](ccw_03_inf.qmd) and [diagnostics/validation](ccw_04_diag.qmd).

3. [Appendix](app_00_summ.qmd): Additional sections include a description of the [synthetic data](app_01_syndata.qmd), [bootstrapping](app_02_boot.qmd), [computation](app_03_speed.qmd) notes and some related methods. [Fitting time-curves](app_04_curvefit.qmd) provides some advanced methods to determine the best-fitting parametric functions for a cumulative incidence curve. 

## Background reading {#reading}

I provide some personal insight into the process, different approaches that can be done, and mainly focus on the analytical methods. In order to actually emulate a target trial, a researcher needs to understand the fundamentals of randomized, controlled trial (RCT) design, causal inference, probability statistics and their practical application with a statistical programming language. I do not go into detail on this.

The following readings are recommended for that background and to prepare for the tutorial guide.

1)  For a full in-depth review of causal inference methods, I recommend Robins' and Hernan's [Causal Inference: What If](https://www.hsph.harvard.edu/miguel-hernan/wp-content/uploads/sites/1268/2024/04/hernanrobins_WhatIf_26apr24.pdf).

2)  [Randomized Controlled Trials](https://www.sciencedirect.com/science/article/pii/S0012369220304633?via%3Dihub) by Emily Zabor et al. provides background on RCT design. Randomization is a key feature which allows a defensible assumption of no confounding. However, another important but often overlooked advantage of RCTs is a well-defined intervention which allows clear causal contrasts to be made (e.g. enroll eligible persons and then give treatment A versus give treatment B). In observational analyses, a well-defined intervention, and the timing of assignment and assessment of eligibility for that intervention are not always aligned in a logical fashion.

3)  Miguel Hernan is a leading expert on TTE and provides a short description of it here: [JAMA 2022](https://doi.org/10.1001/jama.2022.21383). It is a two-step process; first defining the ideal RCT and how it can be emulated in the data, the second step is using TTE methods to perform that emulation (the focus of this guide).

## Troubleshooting your own project

For those having issues with their own CCW projects. I recommend that you download the synthetic data for this project, found here: [Example Data](https://github.com/kmcconeghy/ccwtutorial/blob/main/dta/dta_cloned_panel.Rds). Then follow the CCW code: [Clone-Censor-Weight](ccw_00_summ.qmd) and see if you can replicate my results. Once you can do that, compare the data, modeling and weighting steps to your own project and try to find where differences are. 

For developments notes see [About](about.qmd).

::: {#refs}

:::
