---
title: "Reporting Results"
subtite: "Table 1 Considerations"
---

```{r }
#| label: setup
#| echo: false
#| message: false
#| 
library(here())

source(here('scripts', 'setup.R'), echo=F)
# Set seed for reproducibility
set.seed(42)
```

# Simulation Parameters  

Description of cohort, “Table 1”
	In both randomized trials and observational studies comparing interventions/treatments there is typically a presentation of the overall cohort. Often researchers compare those receiving treatment versus alternatives. The table will present basic demographics and some additional characteristics of interest (confounders, important predictors/causes of outcome etc.). I generally do not present inferential statistics between groups in this table (i.e. no p-values or confidence intervals). At most I will provide a standardized mean difference. This follows some template like below:
Basic “Table 1” set up often found in research manuscripts:


Treatment
No treatment
Age
-
-
Gender
-
-
Chronic condition
-
-
…
-
-


Some special considerations are needed when presenting target trial emulations. 
Sequential target trials 
If conducting sequential daily target trial emulations, even though there may be only 100 unique persons in your study, because you repeatedly use some as controls, the number of observations in the control arm could be substantially larger. Assume 100 unique people analyzed across 2 sequential emulations, and on average 10% get treatment on any given sequence. You can expect ([100 * 0.1] + [90 * 0.1]) = 19 treated, and (90 + 81) = 171 control observations. So how do you present this in the “Table 1”?
One approach is to present every observation. Since baseline is indexed to each sequence this can be important if the baseline information changes across sequences (e.g. a diagnosis is present for one sequence but not the other). However, this can be misleading (inflating sample size) or confusing to the reader especially if they are unfamiliar with emulation methods. It is important to report the number of unique persons and follow-up time if relevant as well as the total number of observations. Other possibilities include randomly selecting one observation per person within each group but analytical methods will lose precision. In the working example, 9 people used as controls in the first sequence, were included in the treatment arm for the second sequence.
Present all observations
Treatment
N=19 
(19 unique people)
No treatment
N=171 
(90 unique people)
Randomly select one observation per person
Treatment
N=19 
No treatment
N=90

Cloning & Grace Period
	The cloning presents an interesting problem for a “Table 1” because the group is identical at baseline. Artificial censoring will change the groups over time as the groups adhere to different treatment strategies. It probably makes sense for most projects using a clone-sensor-weight approach to present a “baseline” cohort column, and then two columns describing the intervention groups at the end of the grace period. Additionally, it makes sense to present the time-invariant covariates as well as time-varying covariates of particular interest (time-varying confounders etc.)
Basic “Table 1” set up for a clone-censor-weight target trial emulation:


Baseline
(N=100)
No treatment at 6 months
(N=50)
Treatment within 6 months
(N=50)
Age
-
-
-
Gender
-
-
-
Hypertension 






Baseline 
-
-
-
Month prior to index
-
-
-


  
::: callout-note
These variables are generated independently, but in real-life would be correlated...
:::