---
title: "Reporting Results"
subtite: "Table 1 Considerations"
---

```{r }
#| label: setup
#| echo: false
#| message: false
#| 
library(here())

source(here('scripts', 'setup.R'), echo=F)
# Set seed for reproducibility
set.seed(42)
```

Application of inverse-probability weighting:

Consider a target trial emulation assigning those eligible for vaccination with Shingrix (RZV) in a nursing home to one of two treatment strategies:

Vaccination with a RZV within 6 months; 
No vaccination through follow-up

The outcome is an incident dementia diagnosis, and individuals censor for non-adherence to treatment strategy, or death

For practicality, we use month units of time, and we assume censoring due to death is non-informative and unaccounted for in the analysis. 

Each person is cloned and assigned to both strategies. For example, consider three persons again:

Person A
Person B
Person C
Vaccinated in month 3
Unvaccinated through follow-up
Vaccinated in month 6



Artificial censoring: abbrev. HZV (vaccination within 9 months), no HZV (none ever)



Person A
Person B
Person C


Vaccinated in month 3
Unvaccinated through follow-up
Vaccinated in month 6


Censoring
Censoring
Censoring
Period
HZV
No HZV
HZV
No HZV
HZV
No HZV
1
0
0
0
0
0
0
2
0
0
0
0
0
0
3
0
1
0
0
0
0
4
0
-
0
0
0
0
5
0
-
0
0
0
0
6
0
-
1
0
0
1


The probability of censoring is intrinsically tied to the probability of initiating treatment because we censor based on adherence to treatment strategy, it might be more appropriate to think of the weighting as “adherence weighting”. 


No HZV strategy:

For the No HZV strategy, the probability of censoring is equal to the probability of initiating treatment (because you are censored if you get the vaccine!). Where V is vaccination, Pr(C) = Pr(Vt=i=1|Vt=i-1=0). Of course,  1 - Pr(C) is the probability of not censoring. The inverse probability of remaining uncensored  is 1 / (1 - Pr[C]) at each timepoint.

Time periods i, from 1 to end of followup, the IPW is 1 / (1 - Pr[C]) = 1 / (1 -Pr[Vt=i=1|Vt=i-1=0])

Period
Probability of censoring
Probability of not censoring
IPW
i = 1,...I, where I is end of follow-up
Pr(C) = Pr(Vt=i=1|Vt=i-1=0)
1 - Pr(C)
1 / (1 - Pr[C])


HZV strategy:

When assigned to vaccination within 6 months, the probability of censoring is 0 for each period up until the end of the grace period (G). 

Period
Probability of censoring
Probability of not censoring
IPW
i= 1, …, 1-G
0
1
1 / 1


This is because we have explicitly stated we are allowing a grace period of time (6 months) before people must be vaccinated. 

At the end of the grace period, the probability of censoring is the probability of not being vaccinated, conditional on not yet receiving the vaccine.

Period
Probability of censoring
Probability of not censoring
IPW
I = 1, …, 1-G
0
1
1 / 1
I = G
Pr(C) = Pr(Vt = G=0|, Vt=G-1=0)
1 - Pr(C)
1 / (Pr[C])


So individuals who are vaccinated in the last period of the grace window are very important, because they are going to be assigned a weight according to the likelihood of receiving vaccination in that period. If the probability of vaccination in the last period given no prior vaccination is very small, 1 - Pr(Vt = G=0|, Vt=G-1=0), then those persons will be assigned very large weights. E.g. if 1% of the sample gets the vaccine at month 6, then the mean of the weights computed for them will be approximately 100 because 1/0.01 = 100. A key consideration is whether folks getting vaccinated in the last period meet causal assumptions of consistency, positivity etc. and you have good data to model the probability of initiation in this  later period (time-varying confounders). 

Note: Conceptually, what we are doing here is emulating a trial where there is perfect adherence to vaccine strategy, but we allow a period of time (grace) before people must be vaccinated. If anyone doesn’t get the vaccine then we essentially force them to receive it at the end of the grace period. This is a somewhat extreme hypothetical, that is commented on by Jamie Robins in the appendix of the Cain article. There is some speculation that alternative weighting strategies could be applied which spread out “forced” vaccination across the grace period, but I have yet to see them in practice.

If a person receives the vaccine prior to month 6, they cannot be censored because they are fully adherent to treatment no matter what happens from that period forward. So if vaccinated prior to the grace period, the weight is 1.

In both cases however, the key estimand is the probability of vaccination at each point of follow-up. This is estimated in the full sample prior to cloning. 

So a model must be fit which estimates probability of vaccination at time period i, given no vaccination in prior time period, baseline covariates (X), time-varying covariates (L), for each point of follow-up. 

Pr(Vt=i=1 | Vt=i-1=0, X, Lt=i-1) 

Once you have that basic probability is it easy to compute the weighting at each timepoint:

Back to our cloned panel:



Person A
Person B
Person C


Vaccinated in month 3
Unvaccinated through follow-up
Vaccinated in month 6


IPW
IPW
IPW
Period
HZV
No HZV
HZV
No HZV
HZV
No HZV
1
1
1 /  Pr(Vt=i=0)
1
1 /  Pr(Vt=i=0)
0
1 /  Pr(Vt=i=0)
2
1
1 /  Pr(Vt=i=0)
1
1 /  Pr(Vt=i=0)
0
1 /  Pr(Vt=i=0)
3
1
-
1
1 /  Pr(Vt=i=0)
0
1 /  Pr(Vt=i=0)
4
1
-
1
1 /  Pr(Vt=i=0)
0
1 /  Pr(Vt=i=0)
5
1
-
1
1 /  Pr(Vt=i=0)
0
1 /  Pr(Vt=i=0)
6
1*
-
-
1 /  Pr(Vt=i=0)
1 / (1 - 
Pr[Vt=i=0])**
-


*Person A is vaccinated at month 3, so their probability of censoring is now 0, 1 - 0 = 1,  1/1 = IPW=1

**Person C is vaccinated in the last period, so their probability of censoring is the conditional probability of not being vaccinated in the 6th period, given no vaccination up to that point. In other words their probability of remaining uncensored, is the probability of initiating treatment in that last period. So 1 / (1 - Pr[C]) is their IPW for this period. They are being weighted to estimate causal effects in a pseudopopulation where person B (who had been censored due to no vaccination) had also been vaccinated at timepoint 6 (a perfectly adherent, “per-procol” estimand).


  
::: callout-note
These variables are generated independently, but in real-life would be correlated...
:::